from typing import Callable

def SetEazyTitle(z:str)->None:...
def Alert(message:str,icon:str)->None:...
def Error(x: str) -> None: ...
def ErrorText(x: str)->None:...
def Info(dih: str) -> None: ...
def Warning(dih: str) -> None: ...
def Ask(dih: str, nih: bool, **l) -> None: ...
def Colored(Color: str, Text: str) -> None: ...
def Beep(Frequency: int, duration: int) -> None: ...
def Countdown(timeleft: int) -> None: ...
def BeepCountdown(timeleft: int) -> None: ...
def Copy(a: str)->None:...
def Paste()->None:...
def Busy(act: str)->None:...
def ReopenAsAdmin()->None:...
def FlashWindow(duration: int)->None:...
def SendNotification(text: str,duration: str)->None:...
def CheckNetwork()->None:...
def CreateQR(content: str,FilePathWithName:str)->None:...
def CreateBarcode(number: int,FilePathWithName: str)->None:...
def TypePrint(text: str)->None:...
def OpenUrl(url:str)->None:...
def OpenInWebview(title: str,url: str)->None:...
def GetUsername()->None:...
def LockWorkStation()->None:...
def Pause()->None:...
def NavigateSettings(x: str)->None:...
def ShowAvailableNetworks()->None:...
def MoveSelfToStartup()->None:...
def GetDateAndTime(x:str)->None:...
def ConvertToMB(data:int,current:str)->None:...
def GetUserDir()->None:...
def SetConsoleTitle(title:str)->None:...
def GetProcessID()->None:...
def GetParentProcessID()->None:...
def TerminateProcess(processID:str)->None:...
def ReadFileAsText(path)->None:...
def ReadFileAsBinary(path:str)->None:...
def WriteFileAsText(path:str,data:str)->None:...
def WriteFileAsBinary(path:str,data:bytes)->None:...
def GetDisplayResolution()->None:...
def BrightText()->None:...

Gigabytes: str
Bytes:str
Kilobytes:str
Bits:str
Terabytes:str

settings_home:str
settings_about:str
settings_system:str
settings_display:str
settings_multitasking:str
settings_clipboard:str
settings_remoteDesktop:str
settings_personalization:str
settings_network:str
settings_network_wifi:str
settings_apps:str
settings_privacy:str
settings_defender:str
settings_security:str
settings_update:str

CautionIcon:int
InfoIcon:int
ErrorIcon:int
QuestionIcon:int

white:str
blue:str
cyan:str
green:str
magenta:str
yellow:str
red:str
black:str
lightwhite:str
lightblue:str
lightcyan:str
lightgreen:str
lightmagenta:str
lightyellow:str
lightred:str
lightblack:str
BGwhite:str
BGblue:str
BGcyan:str
BGgreen:str
BGmagenta:str
BGyellow:str
BGred:str
BGblack:str
BGlightwhite:str
BGlightblue:str
BGlightcyan:str
BGlightgreen:str
BGlightmagenta:str
BGlightyellow:str
BGlightred:str
BGlightblack:str
